Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2023
Var
   numero: real

Inicio
   escreva("Digite um número: ")
   leia(numero)
   se numero > 0 entao
      escreval("O número é positivo")
   senao
      se numero < 0 entao
         escreval("O número é negativo")
      senao
         escreval("O número é zero")
      fimse
   fimse


Fimalgoritmo